### PR TITLE
lock coffee-script version

### PR DESCRIPTION
**Pull request by EndangeredMassa**
When using a range for coffee-script, CI builds will pull in the latest version, build the javascript, then fail the build because there's an unclean git status. We'll lock down the version here so that upgrades are explicit.

### CODE REVIEW

**Comment by jkrems** [comment]
How is this build green and `lib` is deleted? Am I missing something?

**Comment by jkrems** [comment]
`git diff --exit-code` does not include untracked files?

**Comment by jkrems** [comment]
`[[ -z "$(git status -u --porcelain)" ]]` - this seems better. It's an non-zero exit code when there are any uncommitted changes, including untracked files.

**Comment by jkrems** [comment]
Created this as a reminder: https://github.com/EndangeredMassa/npub/issues/28

**Comment by EndangeredMassa** [comment]
Damn. I ran `npm run build` and it exiting fine with no message. I just assumed it worked. I guess npm doesn't let you know when you try to run a script that doesn't exist.

Updated.

**Comment by jkrems** [comment]
:shipit:

**Pull request merged**
