### PR TITLE
make looking for an app optional

### PR DESCRIPTION
**Pull request by EndangeredMassa**
Using testium without a local app to hit is currently problematic. Using the local CLI is also a problem because of this.

This PR makes the app optional. However, there are a lot of conditionals added to the codebase to support this. Some refactoring is probably in order.

---

Addresses: https://github.com/groupon-testium/testium/issues/150

### CODE REVIEW

**Comment by johan** [comment]
Based on the PR description I was expecting worse; this seems at least at the manageable level. Should appless config perhaps have some test case?

**Comment by EndangeredMassa** [comment]
Yup! Added a test for this.

**Comment by EndangeredMassa** [comment]
Tested this in a real app and with different example apps. Seems to work well.

**Comment by EndangeredMassa** [comment]
published in [2.9.1](https://github.com/groupon-testium/testium/releases/tag/v2.9.1)

**Pull request merged**
